{"name": "test_calc2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3.3 == 3.3000000000000003\n  +3.3\n  -3.3000000000000003", "trace": "self = <testing.test_calc.TestCalc object at 0x0366CF10>\n\n    def test_calc2(self):\n        # 调用相加add()方法\n        result = self.calc.add(1.1, 2.2)\n        # 断言 判断是否满足预期结果\n>       assert 3.3 == result\nE       assert 3.3 == 3.3000000000000003\nE         +3.3\nE         -3.3000000000000003\n\ntest_calc.py:37: AssertionError"}, "start": 1602211669433, "stop": 1602211669434, "uuid": "51c89bf1-5c48-44d4-8be9-963a95d74662", "historyId": "e9ebce8320a00e9b92110fb402c9e2fe", "testCaseId": "25faffb114b5deaf52322033011f230d", "fullName": "test_calc.TestCalc#test_calc2", "labels": [{"name": "feature", "value": "计算器加法测试"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "MS-202009291018"}, {"name": "thread", "value": "8252-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc"}]}